apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ee7c
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ee7c
    app.kubernetes.io/part-of: tkrw-pr714-0075-0025-app
  name: devfile-sample-ee7c
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ee7c
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ee7c
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0025-tenant/tkrw-pr714-0075-0025-app/devfile-sample-ee7c@sha256:6812273ce09dc4e072a6e1265343c585172d0fa7f786056e559dfebc1e5c8a2b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
